# Generated by Django 5.2.7 on 2025-10-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
    ]
