# Generated by Django 5.2.7 on 2025-10-31 07:23

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_index', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], max_length=20)),
                ('pay_amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar')], default='NGN', editable=False, max_length=3)),
                ('pay_amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=10)),
                ('estimated_time_seconds', models.IntegerField(default=1800)),
                ('payload', models.JSONField(default=dict)),
                ('verification_strategy', models.CharField(choices=[('ai_only', 'AI Only'), ('peer_consensus', 'Peer Consensus'), ('supervisor', 'Supervisor'), ('hybrid', 'Hybrid')], default='peer_consensus', max_length=20)),
                ('verification_metadata', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('assigned', 'Assigned'), ('submitted', 'Submitted'), ('verifying', 'Verifying'), ('completed', 'Completed'), ('failed', 'Failed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_units', to='projects.enterpriseproject')),
            ],
            options={
                'ordering': ['unit_index'],
                'unique_together': {('project', 'unit_index')},
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.JSONField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('gps_location', models.JSONField(blank=True, null=True)),
                ('supervisor_code', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_details', to='tasks.taskunit')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('photos', models.JSONField()),
                ('supervisor_code', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_verification', to='tasks.taskunit')),
            ],
        ),
        migrations.CreateModel(
            name='TaskValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('validation_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='tasks.taskunit')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('task_unit', 'validator')},
            },
        ),
    ]
