# Generated by Django 5.2.7 on 2025-10-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskvalidation',
            options={'verbose_name': 'Task Validation', 'verbose_name_plural': 'Task Validations'},
        ),
        migrations.AlterUniqueTogether(
            name='taskvalidation',
            unique_together=set(),
        ),
    ]
