# Generated by Django 5.2.7 on 2025-10-31 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_enterprises', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('total_volume_processed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_recorded', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dashboard Snapshot',
                'verbose_name_plural': 'Dashboard Snapshots',
            },
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, choices=[('student_favor', 'In Student Favor'), ('enterprise_favor', 'In Enterprise Favor'), ('partial_refund', 'Partial Refund'), ('full_refund', 'Full Refund'), ('task_reattempt', 'Task Reattempt'), ('dismissed', 'Dismissed')], max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tasks.taskunit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('alert_type', models.CharField(choices=[('payment_issue', 'Payment Issue'), ('verification_failure', 'Verification Failure'), ('system_error', 'System Error'), ('security_alert', 'Security Alert'), ('performance_issue', 'Performance Issue')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_created', 'User Created'), ('user_modified', 'User Modified'), ('project_created', 'Project Created'), ('project_funded', 'Project Funded'), ('task_completed', 'Task Completed'), ('payment_processed', 'Payment Processed'), ('withdrawal_processed', 'Withdrawal Processed'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('dispute_resolved', 'Dispute Resolved'), ('system_config_changed', 'System Configuration Changed')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='admin_dashb_action_7216f7_idx'), models.Index(fields=['user', 'created_at'], name='admin_dashb_user_id_38d420_idx')],
            },
        ),
    ]
